jest.mock('react-native-track-player', () => {
  return {
    __esModule: true,
    default: {
      setupPlayer: jest.fn(),
      add: jest.fn(),
      play: jest.fn(),
      pause: jest.fn(),
      stop: jest.fn(),
      reset: jest.fn(),
      getState: jest.fn(),
      getCurrentTrack: jest.fn(),
      getQueue: jest.fn(),
      getTrack: jest.fn(),
      getDuration: jest.fn(),
      getPosition: jest.fn(),
      seekTo: jest.fn(),
      setVolume: jest.fn(),
      setRate: jest.fn(),
      setRepeatMode: jest.fn(),
      setShuffleMode: jest.fn(),
      getRepeatMode: jest.fn(),
      getShuffleMode: jest.fn(),
      getVolume: jest.fn(),
      getRate: jest.fn(),
      getBufferedPosition: jest.fn(),
      getPlaybackState: jest.fn(),
      getPlaybackMetadata: jest.fn(),
      getPlaybackProgress: jest.fn(),
      getPlaybackQueue: jest.fn(),
      getPlaybackTrack: jest.fn(),
      getPlaybackVolume: jest.fn(),
      getPlaybackRate: jest.fn(),
      getPlaybackBufferedPosition: jest.fn(),
      getPlaybackStateChange: jest.fn(),
      getPlaybackMetadataChange: jest.fn(),
      getPlaybackProgressChange: jest.fn(),
      getPlaybackQueueChange: jest.fn(),
      getPlaybackTrackChange: jest.fn(),
      getPlaybackVolumeChange: jest.fn(),
      getPlaybackRateChange: jest.fn(),
      getPlaybackBufferedPositionChange: jest.fn(),
      getPlaybackStateChangeEvent: jest.fn(),
      getPlaybackMetadataChangeEvent: jest.fn(),
      getPlaybackProgressChangeEvent: jest.fn(),
      getPlaybackQueueChangeEvent: jest.fn(),
      getPlaybackTrackChangeEvent: jest.fn(),
      getPlaybackVolumeChangeEvent: jest.fn(),
      getPlaybackRateChangeEvent: jest.fn(),
      getPlaybackBufferedPositionChangeEvent: jest.fn(),
      getPlaybackStateChangeListener: jest.fn(),
      getPlaybackMetadataChangeListener: jest.fn(),
      getPlaybackProgressChangeListener: jest.fn(),
      getPlaybackQueueChangeListener: jest.fn(),
      getPlaybackTrackChangeListener: jest.fn(),
      getPlaybackVolumeChangeListener: jest.fn(),
      getPlaybackRateChangeListener: jest.fn(),
      getPlaybackBufferedPositionChangeListener: jest.fn(),
      getPlaybackStateChangeSubscription: jest.fn(),
      getPlaybackMetadataChangeSubscription: jest.fn(),
      getPlaybackProgressChangeSubscription: jest.fn(),
      getPlaybackQueueChangeSubscription: jest.fn(),
      getPlaybackTrackChangeSubscription: jest.fn(),
      getPlaybackVolumeChangeSubscription: jest.fn(),
      getPlaybackRateChangeSubscription: jest.fn(),
      getPlaybackBufferedPositionChangeSubscription: jest.fn(),
      getPlaybackStateChangeEmitter: jest.fn(),
      getPlaybackMetadataChangeEmitter: jest.fn(),
      getPlaybackProgressChangeEmitter: jest.fn(),
      getPlaybackQueueChangeEmitter: jest.fn(),
      getPlaybackTrackChangeEmitter: jest.fn(),
      getPlaybackVolumeChangeEmitter: jest.fn(),
      getPlaybackRateChangeEmitter: jest.fn(),
      getPlaybackBufferedPositionChangeEmitter: jest.fn(),
    },
    RepeatMode: {
      Off: 'off',
      Track: 'track',
      Queue: 'queue',
    },
    AppKilledPlaybackBehavior: {
      StopPlaybackAndRemoveNotification: 'stop-playback-and-remove-notification',
    },
  };
});

jest.mock('react-native-localize', () => {
  return {
    getLocales: jest.fn().mockReturnValue([{ countryCode: 'US', languageTag: 'en-US', languageCode: 'en', isRTL: false }]),
    getNumberFormatSettings: jest.fn().mockReturnValue({ decimalSeparator: '.', groupingSeparator: ',' }),
    getCalendar: jest.fn().mockReturnValue('gregorian'),
    getCountry: jest.fn().mockReturnValue('US'),
    getCurrencies: jest.fn().mockReturnValue(['USD']),
    getTemperatureUnit: jest.fn().mockReturnValue('fahrenheit'),
    getTimeZone: jest.fn().mockReturnValue('America/New_York'),
    uses24HourClock: jest.fn().mockReturnValue(false),
    usesMetricSystem: jest.fn().mockReturnValue(false),
    addEventListener: jest.fn(),
    removeEventListener: jest.fn(),
  };
});

jest.mock('react-native-fs', () => {
  return {
    __esModule: true,
    default: {
      readDir: jest.fn(),
      readFile: jest.fn(),
      writeFile: jest.fn(),
      appendFile: jest.fn(),
      unlink: jest.fn(),
      exists: jest.fn(),
      mkdir: jest.fn(),
      moveFile: jest.fn(),
      copyFile: jest.fn(),
      downloadFile: jest.fn(),
      uploadFiles: jest.fn(),
      touch: jest.fn(),
    },
  };
});
