name: react-native-android-build-apk

on:
  push:
    branches:
      - release
permissions: write-all

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: Install npm dependencies using yarn
        run: |
          npm install -g yarn
          yarn install
      - name: Build Android Release
        run: |
          cd android
          chmod +x ./gradlew
          ./gradlew assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.2
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
