name: react-native-android-build-apk

on:
  push:
    tags: 
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
permissions: write-all

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Install npm dependencies using yarn
        run: |
          npm install -g yarn
          yarn install
      - name: Build Android Release
        run: |
          cd android
          chmod +x ./gradlew
          ./gradlew assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.2
        with:
          name: joint-player-android # Name of the artifact (zip file), i.e. joint-player-android.zip
          path: android/app/build/outputs/apk/release/app-release.apk
  
  sentry-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production
          version_prefix: v
          version: ${{ github.ref }}
