name: Release

on:
  push:
    branches:
      - release
  workflow_dispatch:

permissions: write-all

concurrency:
  group: "releases"
  cancel-in-progress: false

jobs:
  release-android:
    name: Release Android
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Setup Java JDK 17 # 需要 Java 17 才能编译 apk, 且默认情况下该环境（ubuntu-latest）只有 Java 11
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: Cache yarn dependencies
        uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies Using yarn
        run: yarn

      - name: Automated Version Bump
        uses: phips28/gh-action-bump-version@v11.0.5
        id: version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          major-wording:  'breaking-change,breaking-changes,breaking,major' # x.0.0
          minor-wording:  'add,new,feature,change,remove' # 0.x.0
          patch-wording:  'patch,fix,bug,bugfix,hotfix' # 0.0.x
          rc-wording:     'release,alpha,beta,rc' # 0.0.x-rc.0
          skip-commit:   true
          skip-tag:      true
          
      - name: Sentry Release
        uses: getsentry/action-release@v1.7.0
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production
          version: ${{ steps.version.outputs.newTag }}
      
      - name: Build Android Release
        run: |
          cd android
          chmod +x ./gradlew
          ./gradlew assembleRelease

      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Release ${{ steps.version.outputs.newTag }}'
          automatic_release_tag: ${{ steps.version.outputs.newTag }}
          files: 'android/app/build/outputs/apk/release/app-release.apk'
