name: Release

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  release-android:
    name: Release Android
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Install Dependencies Using yarn
        run: |
          npm install -g yarn
          yarn install

      - name: Automated Version Bump
        uses: phips28/gh-action-bump-version@v11.0.4
        id: version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          minor-wording:  'add,new,feature,improve,improvement,update,upgrade,change,remove,Update,Upgrade,Change,Remove,Add,New,Feature,Improve,Improvement,Update,Upgrade,Change,Remove'
          major-wording:  'cut-major,breaking-change,breaking-changes,breaking,major'
          patch-wording:  'patch,fix,bug,bugfix,hotfix,security-fix'
          rc-wording:     'RELEASE,alpha,beta,rc'
      
      - name: Sync React Native version
        run: yarn version --new-version ${{ steps.version.outputs.newTag }}

      - name: Sentry Release
        uses: getsentry/action-release@v1.7.0
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production
          version_prefix: v
          version: ${{ steps.version.outputs.newTag }}
      
      - name: Build Android Release
        run: |
          cd android
          chmod +x ./gradlew
          ./gradlew assembleRelease

      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Automatic Release v${{ steps.version.outputs.newTag }}'
          automatic_release_tag: ${{ steps.version.outputs.newTag }}
          files: 'android/app/build/outputs/apk/release/app-release.apk'
