name: Version Bump

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  version-bump:
    name: Version bump of app
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies Using yarn
        run: |
          npm install -g yarn
          yarn install

      - name: Automated Version Bump
        uses: phips28/gh-action-bump-version@v11.0.4
        id: version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          minor-wording:  'add,Adds,new'
          major-wording:  'MAJOR,cut-major'
          patch-wording:  'patch,fixes'     # Providing patch-wording will override commits
                                            # defaulting to a patch bump.
          rc-wording:     'RELEASE,alpha'
          tag-prefix: 'v'
      
      - name: Sync React Native version with package.json Version
        run: yarn version --new-version ${{ steps.version.outputs.newTag }}
        shell: bash
      
      - name: Commit Version Sync Changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'chore:react native - android & ios versions updated'
